#!/usr/bin/env bash
Write a Bash script that displays the content of the file /etc/passwd.
#Your script should only display:
#username
#user id
#Home directory path for the user
#Requirements:
#You must use the while loop (for and until are forbidden)

while IFS=: read -r username userid path;
do
	echo "Username: $username"
	echo "Userid: $userid"
	echo "Path: $path"
done < /etc/passwd
