#!/usr/bin/env bash
#Here is a Bash script that configures an Ubuntu server according to the requirements
# Configure localhost to resolve to 127.0.0.2
# Configure facebook.com to resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/etc/hosts
echo "8.8.8.8		facebook.com" >> ~/etc/hosts
cp -f ~/hosts.new /etc/hosts
