#!/usr/bin/env bash
#Here is a Bash script that configures an Ubuntu server according to the requirements

cp /etc/hosts ~/hosts.new
# Configure localhost to resolve to 127.0.0.2
echo "127.0.0.2		localhost" > ~/etc/hosts

# Configure facebook.com to resolve to 8.8.8.8
echo "8.8.8.8 	facebook.com" >> ~/etc/hosts
cp -f ~/hosts.new /etc/hosts
